# Real products, names and prices read from toffetraktaties.nl/shop/ on 2026-08-19.
# Photos are the client's own product photography.
# cat = the real category the product sits in on their live site.

P = [
 dict(n="Pokémon traktatie met popcorn", p="1,75", f="Pokemon-traktatie-met-popcorn-840x840.jpg",
      s="pokemon-traktatie-met-popcorn", cat="verjaardag", stock=1, pop=1),
 dict(n="Kpop Demon Hunters traktatie", p="1,75", f="Kpop-Demon-Hunters-traktatie-840x840.jpg",
      s="kpop-demon-hunters-traktatie", cat="verjaardag", stock=1, pop=1),
 dict(n="Squid Game traktatie", p="1,90", f="Squid-Game-traktatie-840x840.jpg",
      s="squid-game-traktatie", cat="verjaardag", stock=1, pop=1),
 dict(n="Voetbal traktatie", p="1,95", f="Voetbal-traktatie-840x840.jpg",
      s="voetbal-traktatie", cat="verjaardag", stock=1, pop=1),
 dict(n="Unicorn traktatie beker", p="1,75", f="Unicorn-bekers-840x840.jpg",
      s="unicorn-traktatie-beker", cat="verjaardag", stock=1),
 dict(n="Dino poep traktatie", p="1,70", f="Dino-poep-website-840x840.jpg",
      s="dino-poep-traktatie", cat="verjaardag", stock=1),
 dict(n="Bouwvoertuigen traktatie", p="1,85", f="Bouwvoertuigen-traktatie-840x840.jpg",
      s="bouwvoertuigen-traktatie", cat="verjaardag", stock=1),
 dict(n="Ijshoorntjes traktatie", p="1,75", f="Ijshoorntjes-traktatie-840x840.jpg",
      s="ijshoorntjes-traktatie", cat="verjaardag", stock=1),
 dict(n="Ruimte traktatie", p="1,90", f="Ruimte-traktatie-840x840.jpg",
      s="ruimte-traktatie", cat="verjaardag", stock=1),
 dict(n="Baby Shark traktatie", p="1,70", f="Baby-Shark-traktatie-840x840.jpg",
      s="baby-shark-traktatie", cat="kinderfeestjes", stock=1),
 dict(n="Bootjes traktatie", p="1,80", f="Bootjes-traktatie-840x840.jpg",
      s="bootjes-traktatie", cat="kinderfeestjes", stock=1),
 dict(n="Takkie en Siepie traktatie", p="2,50", f="Takkie-en-Siepie-traktatie-840x840.jpg",
      s="takkie-en-siepie-traktatie", cat="kinderfeestjes", stock=1),
 dict(n="Sanrio traktatie notitieboekje", p="1,90", f="Sanrio-traktatie-notitieboekje-2-840x840.jpg",
      s="sanrio-traktatie-notitieboekje", cat="sanrio-kawaii-traktatie", stock=1),
 dict(n="Pokémon traktatie", p="1,70", f="Pokemon-chipsketting-traktatie-met-sticker-840x840.jpg",
      s="pokemon-traktatie", cat="verjaardag", stock=0),
 dict(n="Zeemeermin chipsketting traktatie", p="1,70", f="Zeemeermin-chipsketting-traktatie-met-sticker-840x840.jpg",
      s="zeemeermin-chipsketting-traktatie", cat="verjaardag", stock=0),
 dict(n="Geboortetraktatie spekjes", p="1,70", f="Geboortetraktatie-spekjes-roze-840x840.jpg",
      s="geboortetraktatie-spekjes", cat="geboorte", stock=1),
 dict(n="Dino afscheidstraktatie", p="1,70", f="Dino-afscheidstraktatie-840x840.jpg",
      s="dino-afscheidstraktatie", cat="afscheid", stock=1),
 dict(n="Ik spetter je gedag afscheidstraktatie", p="1,65", f="Ik-spetter-je-gedag-afscheidstraktatie-840x840.jpg",
      s="ik-spetter-je-gedag-afscheidstraktatie", cat="afscheid", stock=1),
 dict(n="Een meloen keer bedankt", p="3,50", f="Meloen-keer-bedankt-traktatie-840x840.jpg",
      s="een-meloen-keer-bedankt", cat="juf-en-meester", stock=1),
 dict(n="Hartstikke bedankt traktatie", p="3,50", f="Hartstikke-bedankt-traktatie-840x840.jpg",
      s="hartstikke-bedankt-traktatie", cat="juf-en-meester", stock=1),
 dict(n="Hartjeslolly traktatie", p="1,30", f="Hartjeslolly-traktatie-840x840.jpg",
      s="hartjeslolly-traktatie", cat="valentijn", stock=1),
 dict(n="Kersttraktatie badeendje", p="1,90", f="Kersttraktatie-badeend-840x840.jpg",
      s="kersttraktatie-badeendje", cat="kerst", stock=1),
 dict(n="Kersttraktatie kerstpotlood met gum", p="1,90", f="Kersttraktatie-notitieblok-en-potlood-840x840.jpg",
      s="kersttraktatie-kerstpotlood-met-gum", cat="kerst", stock=1),
 dict(n="Kersttraktatie stickers en stuiterbal", p="1,85", f="Kersttraktatie-zuurstok-en-sticker-840x840.jpg",
      s="kersttraktatie-stickers-en-stuiterbal", cat="kerst", stock=1),
 dict(n="Sinterklaas traktatie", p="1,75", f="Sinterklaas-traktatie-840x840.jpg",
      s="sinterklaas-traktatie", cat="kerst", stock=1),
]

# Real categories, exactly as they exist in the client's own navigation.
CATS = [
 ("verjaardag", "Verjaardag", "Voor in de klas of op het kinderdagverblijf"),
 ("juf-en-meester", "Juf en meester", "Bedankjes aan het eind van het jaar"),
 ("afscheid", "Afscheid", "Laatste schooldag en verhuizen"),
 ("geboorte", "Geboorte", "Beschuit met muisjes, maar dan anders"),
 ("kinderfeestjes", "Kinderfeestjes", "Uitdeelzakjes voor het feestje thuis"),
 ("sanrio-kawaii-traktatie", "Sanrio Kawaii", "Hello Kitty en vriendjes"),
 ("valentijn", "Valentijn", "Voor de liefste in de klas"),
 ("kerst", "Kerst", "Kerst en Sinterklaas"),
]
