import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { cookies, headers } from 'next/headers';
import { redirect } from 'next/navigation';
import { loadConfig, secureCompare, type AppConfig } from '@astra/core';

/**
 * Dashboard authentication.
 *
 * Deliberately small and boring. There is exactly one operator during the
 * first rollout, so the design goals are: no session that survives a stolen
 * cookie for long, no way to act by merely following a link from an email,
 * and no dependency that could quietly change how the check behaves.
 *
 * A password (stored only as a scrypt hash) plus an HMAC-signed HttpOnly
 * cookie gets all three. Approval links in email are ordinary URLs: following
 * one lands on the login page unless a valid session already exists.
 */

const SESSION_COOKIE = 'astra_session';
const CSRF_COOKIE = 'astra_csrf';

export interface Session {
  readonly email: string;
  readonly issuedAt: number;
  readonly expiresAt: number;
}

let cachedConfig: AppConfig | undefined;
export function config(): AppConfig {
  cachedConfig ??= loadConfig();
  return cachedConfig;
}

// --- password ---------------------------------------------------------------

/** `scrypt$<saltHex>$<hashHex>`, generated by `npm run dashboard:hash-password`. */
export function hashPassword(password: string, salt = randomBytes(16)): string {
  const derived = scryptSync(password.normalize('NFKC'), salt, 64);
  return `scrypt$${salt.toString('hex')}$${derived.toString('hex')}`;
}

/** Minimum sizes for a stored hash to be considered well formed at all. */
const MIN_SALT_BYTES = 8;
const MIN_HASH_BYTES = 32;

export function verifyPassword(password: string, stored: string): boolean {
  const parts = stored.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return false;
  try {
    const salt = Buffer.from(parts[1] ?? '', 'hex');
    const expected = Buffer.from(parts[2] ?? '', 'hex');

    // A malformed hash decodes to empty buffers, and timingSafeEqual of two
    // empty buffers is true, which would accept *any* password. Reject
    // anything that is not a plausible scrypt output before comparing.
    if (salt.length < MIN_SALT_BYTES || expected.length < MIN_HASH_BYTES) return false;

    const actual = scryptSync(password.normalize('NFKC'), salt, expected.length);
    return timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

// --- session cookie ---------------------------------------------------------

function sign(payload: string): string {
  return createHmac('sha256', config().SESSION_SECRET).update(payload).digest('base64url');
}

export function encodeSession(session: Session): string {
  const payload = Buffer.from(JSON.stringify(session)).toString('base64url');
  return `${payload}.${sign(payload)}`;
}

export function decodeSession(token: string): Session | null {
  const [payload, signature] = token.split('.');
  if (!payload || !signature) return null;
  // Constant-time comparison: a timing oracle on the signature is a forgery
  // oracle on the session.
  if (!secureCompare(signature, sign(payload))) return null;
  try {
    const session = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) as Session;
    if (Date.now() > session.expiresAt) return null;
    // The allowlist is re-checked on every request, so removing an operator
    // from the environment ends their session immediately.
    if (session.email.toLowerCase() !== config().ADMIN_EMAIL.toLowerCase()) return null;
    return session;
  } catch {
    return null;
  }
}

export async function createSession(email: string): Promise<void> {
  const now = Date.now();
  const session: Session = {
    email,
    issuedAt: now,
    expiresAt: now + config().SESSION_MAX_AGE_HOURS * 3600 * 1000,
  };
  const store = await cookies();
  store.set(SESSION_COOKIE, encodeSession(session), {
    httpOnly: true,
    sameSite: 'lax',
    secure: config().APP_ENV === 'production',
    path: '/',
    maxAge: config().SESSION_MAX_AGE_HOURS * 3600,
  });
  store.set(CSRF_COOKIE, randomBytes(32).toString('base64url'), {
    // Readable by the page so the token can be embedded in forms; the cookie
    // alone is useless without also submitting the matching field.
    httpOnly: false,
    sameSite: 'strict',
    secure: config().APP_ENV === 'production',
    path: '/',
    maxAge: config().SESSION_MAX_AGE_HOURS * 3600,
  });
}

export async function destroySession(): Promise<void> {
  const store = await cookies();
  store.delete(SESSION_COOKIE);
  store.delete(CSRF_COOKIE);
}

export async function currentSession(): Promise<Session | null> {
  const token = (await cookies()).get(SESSION_COOKIE)?.value;
  return token ? decodeSession(token) : null;
}

/** Use at the top of every authenticated page and server action. */
export async function requireSession(): Promise<Session> {
  const session = await currentSession();
  if (!session) redirect('/login');
  return session;
}

// --- CSRF -------------------------------------------------------------------

export async function csrfToken(): Promise<string> {
  return (await cookies()).get(CSRF_COOKIE)?.value ?? '';
}

export class CsrfError extends Error {
  constructor() {
    super('CSRF check failed');
    this.name = 'CsrfError';
  }
}

/**
 * Double-submit CSRF check, plus an Origin check. Every state-changing server
 * action calls this before doing anything, so a cross-site form post cannot
 * approve a message on the operator's behalf.
 */
export async function assertCsrf(formData: FormData): Promise<void> {
  const submitted = formData.get('csrf');
  const expected = (await cookies()).get(CSRF_COOKIE)?.value;
  if (typeof submitted !== 'string' || !expected || !secureCompare(submitted, expected)) {
    throw new CsrfError();
  }

  const headerStore = await headers();
  const origin = headerStore.get('origin');
  if (origin && new URL(origin).origin !== new URL(config().APP_BASE_URL).origin) {
    throw new CsrfError();
  }
}

// --- rate limiting ----------------------------------------------------------

const attempts = new Map<string, { count: number; resetAt: number }>();

/**
 * In-process login throttle. Sufficient for a single-operator deployment on
 * one instance; documented in the runbook as something to move to the
 * database if the dashboard is ever scaled out.
 */
export function checkLoginRateLimit(key: string, limit = 5, windowMs = 15 * 60 * 1000): boolean {
  const now = Date.now();
  const entry = attempts.get(key);
  if (!entry || entry.resetAt < now) {
    attempts.set(key, { count: 1, resetAt: now + windowMs });
    return true;
  }
  entry.count += 1;
  return entry.count <= limit;
}

export function resetLoginRateLimit(key: string): void {
  attempts.delete(key);
}

export async function clientKey(): Promise<string> {
  const headerStore = await headers();
  const forwarded = headerStore.get('x-forwarded-for');
  return forwarded?.split(',')[0]?.trim() ?? 'local';
}
