/**
 * Stable machine-readable reasons. These are written to the audit trail and
 * rendered in the dashboard, so they are treated as a public contract: rename
 * with a migration, never reuse a retired code for a different meaning.
 */
export const REASON_CODES = {
  // --- hard boundaries ------------------------------------------------------
  KILL_SWITCH_ON: 'KILL_SWITCH_ON',
  MODE_DISALLOWS_SEND: 'MODE_DISALLOWS_SEND',
  LIVE_SEND_FLAG_OFF: 'LIVE_SEND_FLAG_OFF',
  LIVE_CALENDAR_FLAG_OFF: 'LIVE_CALENDAR_FLAG_OFF',
  LIVE_DEPLOY_FLAG_OFF: 'LIVE_DEPLOY_FLAG_OFF',
  LIVE_WEBHOOK_FLAG_OFF: 'LIVE_WEBHOOK_FLAG_OFF',
  CAMPAIGN_NOT_ENABLED: 'CAMPAIGN_NOT_ENABLED',
  EXCLUSION_ACTIVE: 'EXCLUSION_ACTIVE',
  SUPPRESSED_CONTACT: 'SUPPRESSED_CONTACT',

  // --- ownership ------------------------------------------------------------
  OWNER_NOT_ASTRA: 'OWNER_NOT_ASTRA',
  OWNER_UNKNOWN: 'OWNER_UNKNOWN',
  SEQUENCE_OWNS_CONVERSATION: 'SEQUENCE_OWNS_CONVERSATION',
  SUBSTANTIVE_STEP_PLANNED: 'SUBSTANTIVE_STEP_PLANNED',
  SEQUENCE_BRANCH_UNRESOLVABLE: 'SEQUENCE_BRANCH_UNRESOLVABLE',
  PAUSE_FAILED: 'PAUSE_FAILED',
  PAUSE_UNVERIFIED: 'PAUSE_UNVERIFIED',
  OWNERSHIP_ACQUIRED: 'OWNERSHIP_ACQUIRED',
  PENDING_MANUAL_TASK: 'PENDING_MANUAL_TASK',

  // --- freshness / concurrency ---------------------------------------------
  CONVERSATION_CHANGED: 'CONVERSATION_CHANGED',
  STALE_CONVERSATION_HASH: 'STALE_CONVERSATION_HASH',
  STALE_INBOUND_MESSAGE_ID: 'STALE_INBOUND_MESSAGE_ID',
  STALE_APPROVAL: 'STALE_APPROVAL',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  APPROVAL_MISSING: 'APPROVAL_MISSING',
  APPROVAL_HASH_MISMATCH: 'APPROVAL_HASH_MISMATCH',
  DUPLICATE_EVENT: 'DUPLICATE_EVENT',
  LOCK_NOT_ACQUIRED: 'LOCK_NOT_ACQUIRED',

  // --- conversation understanding ------------------------------------------
  UNCERTAIN_DIRECTION: 'UNCERTAIN_DIRECTION',
  UNCERTAIN_CHANNEL: 'UNCERTAIN_CHANNEL',
  LOSSY_TRUNCATION: 'LOSSY_TRUNCATION',
  ATTACHMENT_PRESENT: 'ATTACHMENT_PRESENT',
  THIRD_PARTY_PARTICIPANT: 'THIRD_PARTY_PARTICIPANT',
  UNKNOWN_CC: 'UNKNOWN_CC',
  EXTERNAL_CONTEXT_SUSPECTED: 'EXTERNAL_CONTEXT_SUSPECTED',
  MEETING_ALREADY_REFERENCED: 'MEETING_ALREADY_REFERENCED',
  HIGH_RAPPORT: 'HIGH_RAPPORT',
  TURN_LIMIT_REACHED: 'TURN_LIMIT_REACHED',
  AUTOMATED_OUTBOUND_CAP_REACHED: 'AUTOMATED_OUTBOUND_CAP_REACHED',
  MISSING_LEAD_OR_CAMPAIGN: 'MISSING_LEAD_OR_CAMPAIGN',

  // --- model output ---------------------------------------------------------
  CONFIDENCE_BELOW_THRESHOLD: 'CONFIDENCE_BELOW_THRESHOLD',
  RISK_NOT_LOW: 'RISK_NOT_LOW',
  SAFETY_FLAG_SET: 'SAFETY_FLAG_SET',
  MODEL_SCHEMA_INVALID: 'MODEL_SCHEMA_INVALID',
  INTENT_NOT_ALLOWLISTED: 'INTENT_NOT_ALLOWLISTED',
  NO_MATCHING_LOW_RISK_CASE: 'NO_MATCHING_LOW_RISK_CASE',
  ACTION_REQUIRES_APPROVAL: 'ACTION_REQUIRES_APPROVAL',
  PROMPT_INJECTION_DETECTED: 'PROMPT_INJECTION_DETECTED',

  // --- message content ------------------------------------------------------
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',
  WORD_LIMIT_EXCEEDED: 'WORD_LIMIT_EXCEEDED',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  UNRESOLVED_PLACEHOLDER: 'UNRESOLVED_PLACEHOLDER',
  URL_NOT_PERMITTED: 'URL_NOT_PERMITTED',
  PROTOTYPE_URL_REQUIRES_APPROVAL: 'PROTOTYPE_URL_REQUIRES_APPROVAL',
  PROHIBITED_PHRASE: 'PROHIBITED_PHRASE',
  FABRICATED_SOCIAL_PROOF: 'FABRICATED_SOCIAL_PROOF',
  GUARANTEE_LANGUAGE: 'GUARANTEE_LANGUAGE',
  FAKE_URGENCY: 'FAKE_URGENCY',
  STYLE_VIOLATION: 'STYLE_VIOLATION',
  UNSUPPORTED_CLAIM: 'UNSUPPORTED_CLAIM',
  NEW_PROMISE: 'NEW_PROMISE',
  PRICING_OR_SCOPE: 'PRICING_OR_SCOPE',
  SENSITIVE_DATA: 'SENSITIVE_DATA',
  CONTENT_HASH_MISMATCH: 'CONTENT_HASH_MISMATCH',
  MISSING_REPLY_TO_ACTIVITY_ID: 'MISSING_REPLY_TO_ACTIVITY_ID',
  MISSING_SEND_IDENTIFIERS: 'MISSING_SEND_IDENTIFIERS',
  CONCEPT_BRIEF_MISSING: 'CONCEPT_BRIEF_MISSING',

  // --- calendar -------------------------------------------------------------
  CALENDAR_QUERY_FAILED: 'CALENDAR_QUERY_FAILED',
  CALENDAR_DATA_STALE: 'CALENDAR_DATA_STALE',
  NO_SLOTS_AVAILABLE: 'NO_SLOTS_AVAILABLE',
  SLOT_NO_LONGER_FREE: 'SLOT_NO_LONGER_FREE',
  SLOT_RESERVED_ELSEWHERE: 'SLOT_RESERVED_ELSEWHERE',
  AMBIGUOUS_SLOT_SELECTION: 'AMBIGUOUS_SLOT_SELECTION',
  MISSING_ATTENDEE_EMAIL: 'MISSING_ATTENDEE_EMAIL',
  CALENDAR_NOT_CONNECTED: 'CALENDAR_NOT_CONNECTED',
  EVENT_CREATION_FAILED: 'EVENT_CREATION_FAILED',

  // --- prototype ------------------------------------------------------------
  NO_PRIOR_PROTOTYPE_OFFER: 'NO_PRIOR_PROTOTYPE_OFFER',
  PROTOTYPE_QA_FAILED: 'PROTOTYPE_QA_FAILED',
  PROTOTYPE_DEPLOY_FAILED: 'PROTOTYPE_DEPLOY_FAILED',
  COMPANY_IDENTITY_AMBIGUOUS: 'COMPANY_IDENTITY_AMBIGUOUS',
  WEBSITE_INACCESSIBLE: 'WEBSITE_INACCESSIBLE',

  // --- allow ----------------------------------------------------------------
  ALLOWED_LOW_RISK_CASE: 'ALLOWED_LOW_RISK_CASE',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
